nelmio_api_doc:
    documentation:
        info:
            title: Template
            description: Basic template
            version: 1.0.0
        servers:
            - url: http://127.0.0.1
              description: API dev path
    areas:
        path_patterns:
            - ^\/api(?!\/doc(\.json)?$)